[package]
name = "minigrep_rd"
version = "0.1.0"
edition = "2024"
description = "A simple tool for searching through lines of text."
license = "MIT OR Apache-2.0"

[dependencies]

[[bin]]
name = "minigrep"
path = "src/main.rs"
